dataset:
  name: cifar100
  num_tasks: 5
  classes_per_task: 20

training:
  model: resnet34
  epochs_per_task: 16
  batch_size: 128
  lr: 0.01
  optimizer: sgd
  momentum: 0.9
  weight_decay: 5e-4
  augment: true
  mixup_alpha: 0.1
  scheduler:
    step_size: 4
    gamma: 0.5

method: ucm

ucm:
  pretrain_foundation: true
  pretrain_dataset: "task1"
  pretrain_method: "supervised"
  pretrain_epochs: 2